/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.LD.Windows.ChooseFile;

import com.LD.Windows.Main.FirstS;
import com.LD.Windows.Main.FirstW;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.File;

/**
 *
 * @author Mr-LiZhuo
 */
public class ChooseCalFile extends javax.swing.JFrame {

    /**
     * Creates new form ChooseCalFile
     */
    ChooseFile fi;
    FirstW fj;
    FirstS fs;
    int sa;
    Image ic = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/com/LD/img/ic.png"));

    public ChooseCalFile(ChooseFile fi, FirstW fj, int sa) {
        this.fi = fi;
        this.fj = fj;
        this.sa = sa;
        initComponents();
    }

    public ChooseCalFile(ChooseFile fi, FirstS fs, int sa) {
        this.fi = fi;
        this.fs = fs;
        this.sa = sa;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Choose Calculation File(s) :");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jFileChooser1.setCurrentDirectory(new java.io.File("C:\\"));
            jFileChooser1.setFileSelectionMode(javax.swing.JFileChooser.FILES_AND_DIRECTORIES);
            jFileChooser1.setMultiSelectionEnabled(true);
            jFileChooser1.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jFileChooser1ActionPerformed(evt);
                }
            });

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jFileChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            );
            layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jFileChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            );

            this.setIconImage(ic);

            pack();
            setLocationRelativeTo(null);
        }// </editor-fold>//GEN-END:initComponents

    private void jFileChooser1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFileChooser1ActionPerformed
        // TODO add your handling code here:

        if (jFileChooser1.getSelectedFile() == null) {
            fi.setVisible(true);
            dispose();
        } else {

            File[] files = jFileChooser1.getSelectedFiles();
            String tempname = "";
            String temppath = "";

            if (files[0].isFile() == true) {
                for (int a = 0; a < files.length; a++) {
                    if (a == files.length - 1) {
                        String te = files[a].getName().substring(files[a].getName().lastIndexOf(".") + 1);
                        if (te.startsWith("gz") || te.startsWith("vcf") || te.startsWith("map") || te.startsWith("ped")) {
                            tempname = tempname + files[a].getName();
                            temppath = temppath + files[a].getPath();
                        }
                    } else {
                        String te = files[a].getName().substring(files[a].getName().lastIndexOf(".") + 1);
                        if (te.startsWith("gz") || te.startsWith("vcf") || te.startsWith("map") || te.startsWith("ped")) {
                            tempname = tempname + files[a].getName() + ",";
                            temppath = temppath + files[a].getPath() + ",";
                        }
                    }
                }
            } else {
                File[] array = files[0].listFiles();
                for (int is = 0; is < array.length; is++) {
                    String te = array[is].getName().substring(array[is].getName().lastIndexOf(".") + 1);
                    if (te.startsWith("gz") || te.startsWith("vcf") || te.startsWith("map") || te.startsWith("ped")) {
                        temppath = temppath + array[is] + "/" + array[is].getName() + ",";
                        tempname = tempname + array[is].getName() + ",";
                    }
                }
                temppath = temppath.substring(0, temppath.length() - 1);
                tempname = tempname.substring(0, tempname.length() - 1);
            }

            String[] calna = tempname.split(",");
            String[] calpa = temppath.split(",");
            if (sa == 1) {
                for (int i = 0; i < calna.length; i++) {
                    fj.setInputName(calna[i], calpa[i], 1);
                }
            } else {
                for (int i = 0; i < calna.length; i++) {
                    fs.setInputName(calna[i], calpa[i], 1);
                }

            }

            // fi.setCalname(tempname);
            //fi.setCalpath(temppath);
            fi.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_jFileChooser1ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        fi.setVisible(true);
        dispose();
    }//GEN-LAST:event_formWindowClosing

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFileChooser jFileChooser1;
    // End of variables declaration//GEN-END:variables
}
